name: push

on:
  push:
    branches:
      - main

concurrency:
  group: push-${{github.ref}}-${{github.run_number}}-${{github.workflow}}
  cancel-in-progress: true

jobs:
  build-full:
    uses: ./.github/workflows/build-full.yml
  all:
    needs: [build-full]
    runs-on: ubuntu-latest
    steps:
    - name: Success
      run: "true"

# vim: set nowrap tw=100:
